server:
  port: 9090
  servlet:
    context-path: /auto-ml-creator/v1

spark:
  home:
  master-uri: local[*]

spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/automlcreatordb
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      file-size-threshold: 2KB
      max-request-size: 1GB
file:
  upload-dir: /Users/veron/auto-ml-creator/uploads/
logging:
  level:
    com.veryastr.bsu: debug
